name: UmeAiRT
channels:
  - conda-forge
  - pytorch
  - nvidia
  - defaults
channel_priority: strict
dependencies:
  - python=3.12.12
  - git
  - nvidia::cuda-toolkit=12.9.1
  - pip
  - ninja
  - ccache
  - c-compiler
  - cxx-compiler
  - conda-forge::aria2
